repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.263
    hooks:
      - id: ruff
        args: [--fix]


  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
